### PR TITLE
feat(bounty): Add frontend NextJS on Akash deployment guide

### PR DESCRIPTION
**Pull request by 0xFable**
Related to [Documentation Bounties](https://github.com/InterWasm/DAO/blob/main/BOUNTIES.md)

Added a new repo which started as a create-react-app with nextjs and we go through the journey or composing that into a docker container, pushing that so it can be used by an Akash deployment then going through the deployment. 

Repo is here: https://github.com/0xFable/nextjs-akash-boilerplate
Feedback welcome :D

### CODE REVIEW

**Comment by 0xFable** [comment]
Hi @the-frey @JakeHartnell any chance of a review? 🚀

**Comment by 0xFable** [comment]
@orkunkl what about you good ser?

**Comment by orkunkl** [comment]
@findolor You are pretty hyped for akash, why not give this a review?

**Comment by findolor** [comment]
@0xFable Let me take a look at it and I'll give you a review!

**Comment by findolor** [comment]
@0xFable First of all thank you for documenting!

I was successful at deployment using the app in given repo. I haven't tried the SSL yet so can't say anything on that part. Should be fairly simple I believe.

It was easy going through to Akash documentation but maybe you can have more code examples in this repo too. I think some snippets/images would be better to understand for the average user.

**Comment by 0xFable** [comment]
Hey @findolor ! Thank you for review!! 
No problem I can try to find some more images to give a more visual look on how it goes.

**Comment by findolor** [comment]
At the same time why not check out https://docs.akash.network/guides/deploy

This is more user friendly compared to using CLI

**Comment by 0xFable** [comment]
Had a look at the deploy app, very cool. As a result I have opened a PR in awesome-akash to get this added as a template people can select 

image

**Comment by 0xFable** [comment]
Hey all :), made some updates to the repo to make the thing more complete, as a result we now have: 
+ A code-base guide entirely through CLI with examples
+ A image-led guide through the Akashlytics app for those that don't wanna code
+ Added the nextjs deploy file [here](https://github.com/ovrclk/awesome-akash/pull/257). Once this is merged NextJS should appear as a template 

:D

**Review by findolor — APPROVED** [review]
LGTM!

**Comment by 0xFable** [comment]
@orkunkl @JakeHartnell :D

**Comment by 0xFable** [comment]
Hey @findolor, no worries! Updated the PR with the wallet addr again

**Comment by orkunkl** [comment]
Done! https://daodao.zone/multisig/juno1kkvct82dl0afp7lv2v6wv6emgltwqywxw2xu7p0l0vvl8rquv94s7e6xss/proposals/4

**Pull request merged**
